### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by decarlof** [csyben/PYRO-NN#1]
I followed your installation instruction but when running the example:

```
python examples/ct_reconstruction/example_parallel_2d.py 
/anaconda3/lib/python3.6/site-packages/pyronn/__init__.py:19: UserWarning: Could not import PYRO-NN-Layers. Please install PYRO-NN-Layers from www.github.com/csyben/pyRO-NN-Layers
  warnings.warn('Could not import PYRO-NN-Layers. Please install PYRO-NN-Layers from www.github.com/csyben/pyRO-NN-Layers')
Traceback (most recent call last):
  File "examples/ct_reconstruction/example_parallel_2d.py", line 19, in <module>
    from pyronn.ct_reconstruction.layers.projection_2d import parallel_projection2d
  File "anaconda3/lib/python3.6/site-packages/pyronn/ct_reconstruction/layers/projection_2d.py", line 16, in <module>
    import pyronn_layers
ModuleNotFoundError: No module named 'pyronn_layers'


```

I looked into installing pyronn_layers from [here](https://github.com/csyben/pyRO-NN-Layers) but this requires to rebuild Tensorflow and then patch the Tensorflow build process such that all C++ and CUDA files in the pyronn_layers folder are compiled and made available under the pyronn_layers namespace at the python level.

Am I on the right path?

**Comment by csyben** [comment]
Hi,

yes, that is the case. You could also follow the Tensorflow guide and create the operations separately from Tensorflow, but then you have to match all versions of CUDA, CUDNN, GCC, etc. which are used for the Tensorflow package in the pip repositories. Creating Tensorflow from the sources avoids this problem, so we decided to connect directly to the build process of Tensorflow. 

Currently, our patch only works to build on Linux systems. A pre-built binary for Ubuntu with Cuda 10 and CUDNN 7.2 is uploaded to the pyronn_layers repository. We plan to support the Windows build in the near future.

**Comment by decarlof** [comment]
thanks a lot, this address my question, will do.
