### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by aQib-jahan** [csyben/PYRO-NN#11]
Hello!
Is there any installation issue? I'm having this problem when trying to install via pip command.
![Capture](https://user-images.githubusercontent.com/55131976/93021297-b3cb4780-f603-11ea-989d-4f110e40230e.PNG)
Can you please mention the compatible tensorflow and python version for this to be installed? (for windows)

**Comment by csyben** [comment]
The layers itself are currently only precompiled and shipped via the pip repository for linux. For Windows you need to built from sources according to the tensorflow custom-op guide.
