### ISSUE TITLE
Install error (could not find version 0.1.0)

### ISSUE THREAD

**Issue by lxaibl** [csyben/PYRO-NN#12]
<img width="484" alt="Capture" src="https://user-images.githubusercontent.com/11236724/93789846-fab6cf80-fbf7-11ea-9a61-74c0e2f218e4.PNG">

**Comment by csyben** [comment]
Hi,

could you give some information about you system ?
Could you try to install pyronn within a virtual environment with a python 3.6 version ? I observed a problem with python 3.8.

best
Christopher

**Comment by lxaibl** [comment]
I use Anaconda 4.8 on linux system. I create a conda environment with
python 3.7,  and cuda10.1, cudnn7.6-cuda10.1, pip 20.2, and tensorflow 2 to
pip install pyronn.
Do you think create a conda environment with python 3.6 would solve
the problem?

**Comment by csyben** [comment]
I think with 3.6 it should work. I am currently investigating the packaging of the Python package, as I suspect it is a bug in the process. The PYRONN package depends on the pyronn-layers package, but with python3.8 a version check seems to have failed, but actually the framework should work with 3.7 and 3.8 as well. Until I find the bug and release a fixed package, I assume 3.6 is the right way, sorry for the inconvenience.

**Comment by csyben** [comment]
I updated the pyronn-layer package. Should work now for python3.6, 3.7 and 3,8

best
