### ISSUE TITLE
Truncation artifacts

### ISSUE THREAD

**Issue by YZST** [csyben/PYRO-NN#13]
Hello. I have tried to use pyronn to reconstruct CBCTs using projections with limited field of view, which generated images with very severe truncation artifacts. I am wondering if you may help to provide any insights of the potential cause? Thanks!
![Truncation](https://user-images.githubusercontent.com/39815277/101186619-f0ae4580-3618-11eb-9801-7daffaa7c833.jpg)

**Comment by csyben** [comment]
Did you setup the geometry correctly ?Or does the truncation comes from your data ?

**Comment by YZST** [comment]
> Did you setup the geometry correctly ?Or does the truncation comes from your data ?

Hi, I used the standard circular cone-beam geometry. I found the same issue with the digital phantom provided in the Pyronn package when the field is truncated.
