### ISSUE TITLE
The problem of missing functions in ''pyronn.ct_reconstruction.layers.projection_3d ''

### ISSUE THREAD

**Issue by reason1984** [csyben/PYRO-NN#22]
Hello!  It is shown that ''par_projection3d'' function is not in ''pyronn.ct_reconstruction.layers.projection_3d'' package during operation, causing example_parallel_3d.py to report an error of missing functions? What is the reason for this? Thanks for the answer.

**Comment by csyben** [comment]
Hi,

unfortunatly the 3D parallel projektion operator is not implemented in the pyronn layers package. There is a version of it in the dev-branch of the pyronn-layers repository. You could build the layer by your own if needed.

**Comment by reason1984** [comment]
Thank you very much!
