### ISSUE TITLE
Use as plugin loss function 

### ISSUE THREAD

**Issue by utkarsh1705** [csyben/PYRO-NN#7]
Hi,
Thanks for the work.

My doubt is given sinograms of say n*n dim each, can fan_backprojection2d take m such sinograms and produce corresponding outputs. As I am thinking of using this as a loss function and the input will be BatchSize*n*n.

Thank you

**Comment by csyben** [comment]
Hi,

currently there is no support for a batch size. Which means you would need to loop over the layer on the python level using e.g. tf.while .
Alternatively you can add the batch support in the C++ class for the backprojection2d if you compile the pyro-nn-layers by your own.

Currently it is planned to provide batch support after the upgrade to TF2.0 is finished, this could take some few more weeks.

**Comment by csyben** [comment]
Batch size is now supported for all Layers with the new update 0.1.0. Also TF2.0 and eager execution are supported now. Does that update fix your trouble?

**Comment by utkarsh1705** [comment]
Hi,
I was able to use this with TF2.0 and eager execution for my work. 

Thanks a lot.
