### ISSUE TITLE
gradient check of the implementation

### ISSUE THREAD

**Issue by lidaiqing** [csyben/PYRO-NN#8]
Hi @csyben , quick question, did you have a chance to do gradient check using numerical method? Does it pass within certain accuracy?

Best,
Daiqing

**Comment by csyben** [comment]
Hi, 
we did a gradient check at the beginning with the tensorflow methods, and they passed. Currently we are preparing the update towards Tensorflow 2.0 and eager execution support. It is planned to provide the gradient checks with the update.
best,
Christopher

**Comment by lidaiqing** [comment]
Hey Christopher,

Thank you for your reply! It did not pass when I first test it but later I found out it is the issue of requirement of precisions. Thanks!

Daiqing
