### ISSUE TITLE
malloc assertion failed

### ISSUE THREAD

**Issue by AlexandruMoraru310** [csyben/PYRO-NN#9]
Hello,

I tried to run some scripts in the examples/ct_reconstruction folder. I tried example_parallel_2d.py, example_fan_2d.py and example_fan_2d_shortscan.py. All of them give runtime error at the line:

`sinogram = parallel_projection2d(phantom, geometry)`

 The error is:

`python: malloc.c:2385: sysmalloc: Assertion (old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0) failed.`

Any idea for a workaround?

**Comment by csyben** [comment]
Could you check which Tensorflow version you have currently installed? I stumbled across a possible problem with TensorFlow 2.2 today. Could you check if the problem is solved when you use Tensorflow 2.1 instead of 2.2?

**Comment by AlexandruMoraru310** [comment]
With TensorFlow version 2.1 everything works just fine. Thank you!
